import XCTest
@testable import CRUXCore

/// Layer-by-layer Swift/Python parity on frozen fixtures generated by
/// `tools/export_parity_fixture.py`:
/// 1. preprocess: synthetic RGBA -> torchvision v2 reference tensor.
/// 2. decode: real FP16 ONNX outputs -> Python decode reference
///    (conf/class/bbox + two-stage bilinear mask RLE).
/// 3. lab: synthetic pattern + full-bbox holds -> median Lab reference.
final class ParityTests: XCTestCase {
    private var fixtureURL: URL {
        URL(fileURLWithPath: "Tests/CRUXCoreTests/Fixtures")
    }

    // MARK: preprocess

    func testPreprocessMatchesPythonTorchvisionReference() throws {
        let rgba = try Data(contentsOf: fixtureURL.appending(path: "parity_synth_rgba.bin"))
        let reference = try floats(contentsOf: "parity_preprocess_synth.bin")
        let synthW = 200, synthH = 150, size = 648
        XCTAssertEqual(rgba.count, synthW * synthH * 4)
        XCTAssertEqual(reference.count, 3 * size * size)

        let swift = try XCTUnwrap(
            SegmentationPreprocessor.preprocess(
                rgba: Array(rgba), width: synthW, height: synthH, size: size
            )
        )
        XCTAssertEqual(swift.count, reference.count)
        var maxAbs: Float = 0
        for (a, b) in zip(swift, reference) {
            maxAbs = max(maxAbs, abs(a - b))
        }
        XCTAssertLessThan(maxAbs, 1e-4, "preprocess tensor drift vs Python")
    }

    // MARK: decode

    func testDecodeMatchesPythonReference() throws {
        let outputs = try floats(contentsOf: "parity_model_outputs.bin")
        let reference = try JSONDecoder().decode(
            DecodeReference.self,
            from: Data(contentsOf: fixtureURL.appending(path: "parity_decode_reference.json"))
        )
        let maskSize = 648 / 4
        let dets = Array(outputs[0..<400])
        let labels = Array(outputs[400..<700])
        let masks = Array(outputs[700..<(700 + 100 * maskSize * maskSize)])

        let result = try XCTUnwrap(
            SegmentationDecoder.decode(
                dets: dets, labels: labels, masks: masks,
                imageWidth: reference.imageWidth,
                imageHeight: reference.imageHeight,
                inputSize: 648,
                modelVersion: "parity-fixture"
            )
        )
        XCTAssertEqual(result.detections.count, reference.holds.count,
                       "detection count drift vs Python")

        var worstMaskIoU: Double = 1
        for (hold, ref) in zip(result.detections, reference.holds) {
            XCTAssertEqual(hold.id, ref.queryIndex, "query index order drift")
            XCTAssertEqual(hold.confidence, Float(ref.conf), accuracy: 1e-5)
            let expectedKind: HoldKind = ref.cls == 0 ? .hold : .volume
            XCTAssertEqual(hold.kind, expectedKind)
            XCTAssertEqual(hold.geometry.bboxX, ref.x1, accuracy: 1e-6)
            XCTAssertEqual(hold.geometry.bboxY, ref.y1, accuracy: 1e-6)
            XCTAssertEqual(hold.geometry.bboxWidth, ref.x2 - ref.x1, accuracy: 1e-6)
            XCTAssertEqual(hold.geometry.bboxHeight, ref.y2 - ref.y1, accuracy: 1e-6)
            XCTAssertEqual(hold.geometry.maskWidth, ref.maskW)
            XCTAssertEqual(hold.geometry.maskHeight, ref.maskH)

            let swiftBitmap = decodeRLE(
                hold.geometry.maskRLE,
                width: hold.geometry.maskWidth,
                height: hold.geometry.maskHeight
            )
            let pyBitmap = bitmap(rle: ref.rle,
                                  width: ref.maskW, height: ref.maskH)
            let current = iou(swiftBitmap, pyBitmap)
            worstMaskIoU = min(worstMaskIoU, current)
        }
        XCTAssertEqual(worstMaskIoU, 1.0,
                       "worst mask IoU vs Python (two-stage bilinear)")
    }

    // MARK: lab

    func testMedianLabMatchesPythonReference() throws {
        let rgba = try Data(contentsOf: fixtureURL.appending(path: "parity_synth_rgba.bin"))
        let reference = try JSONDecoder().decode(
            LabReference.self,
            from: Data(contentsOf: fixtureURL.appending(path: "parity_lab_reference.json"))
        )

        let detections = reference.holds.map { ref in
            DetectedHold(
                id: 0,
                kind: .hold,
                confidence: 0.9,
                geometry: HoldGeometry(
                    bboxX: ref.bboxX, bboxY: ref.bboxY,
                    bboxWidth: ref.bboxW, bboxHeight: ref.bboxH,
                    maskWidth: ref.maskW, maskHeight: ref.maskH,
                    maskRLE: rleData(ref.rle)
                )
            )
        }
        let segmentation = SegmentationResult(
            modelVersion: "parity-fixture", inputSize: 648, detections: detections
        )
        let analysis = try HoldColorAnalyzer().analyze(
            segmentation: segmentation,
            imageWidth: reference.imageWidth,
            imageHeight: reference.imageHeight,
            imagePixels: { x, y in
                let offset = (y * reference.imageWidth + x) * 4
                guard offset + 2 < rgba.count else { return nil }
                return SRGBColor(
                    red: Double(rgba[offset]),
                    green: Double(rgba[offset + 1]),
                    blue: Double(rgba[offset + 2])
                )
            }
        )

        for (hold, ref) in zip(analysis.holds, reference.holds) {
            XCTAssertEqual(hold.referenceLab.l, ref.lab.l, accuracy: 1e-4)
            XCTAssertEqual(hold.referenceLab.a, ref.lab.a, accuracy: 1e-4)
            XCTAssertEqual(hold.referenceLab.b, ref.lab.b, accuracy: 1e-4)
        }
    }

    // MARK: helpers

    private func floats(contentsOf name: String) throws -> [Float] {
        let data = try Data(contentsOf: fixtureURL.appending(path: name))
        return data.withUnsafeBytes { rawBuffer in
            Array(rawBuffer.bindMemory(to: Float.self))
        }
    }

    private func rleData(_ counts: [Int32]) -> Data {
        counts.withUnsafeBytes { Data($0) }
    }

    private func decodeRLE(_ data: Data, width: Int, height: Int) -> [UInt8] {
        let total = width * height
        guard total > 0 else { return [] }
        var out = [UInt8](repeating: 0, count: total)
        let counts: [Int32] = data.withUnsafeBytes { Array($0.bindMemory(to: Int32.self)) }
        var idx = 0
        var value = 0
        for count in counts {
            let c = Int(count)
            if c < 0 || idx + c > total { return [] }
            if value == 1 {
                for j in idx..<(idx + c) { out[j] = 1 }
            }
            idx += c
            value = 1 - value
        }
        return out
    }

    private func bitmap(rle: [Int32], width: Int, height: Int) -> [UInt8] {
        var out = [UInt8](repeating: 0, count: width * height)
        var idx = 0
        var value = 0
        for count in rle {
            let c = Int(count)
            if value == 1 {
                for j in idx..<(idx + c) { out[j] = 1 }
            }
            idx += c
            value = 1 - value
        }
        return out
    }

    private func iou(_ a: [UInt8], _ b: [UInt8]) -> Double {
        guard a.count == b.count, !a.isEmpty else { return 0 }
        var inter = 0
        var union = 0
        for (x, y) in zip(a, b) {
            if x == 1 || y == 1 { union += 1 }
            if x == 1 && y == 1 { inter += 1 }
        }
        return union == 0 ? 1 : Double(inter) / Double(union)
    }
}

// MARK: fixture DTOs

private struct DecodeReference: Codable {
    let imageWidth: Int
    let imageHeight: Int
    let holds: [DecodeHold]
}

private struct DecodeHold: Codable {
    let queryIndex: Int
    let conf: Double
    let cls: Int
    let x1: Double
    let y1: Double
    let x2: Double
    let y2: Double
    let maskW: Int
    let maskH: Int
    let rle: [Int32]
}

private struct LabReference: Codable {
    let imageWidth: Int
    let imageHeight: Int
    let holds: [LabHold]
}

private struct LabHold: Codable {
    let bboxX: Double
    let bboxY: Double
    let bboxW: Double
    let bboxH: Double
    let maskW: Int
    let maskH: Int
    let rle: [Int32]
    let lab: LabValue
}

private struct LabValue: Codable {
    let l: Double
    let a: Double
    let b: Double
}
